"""Add vendor_profile_id to Project

Revision ID: 1931a21ff697
Revises: e64a4a576d35
Create Date: 2025-12-08 17:15:14.779439

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1931a21ff697'
down_revision = 'e64a4a576d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('vendor_profile_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'project', 'vendorprofile', ['vendor_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'vendor_profile_id')
    # ### end Alembic commands ###
