"""Change column name vendor_id in ProjectVendorRequest model to vendor_profile_id to make it more clear

Revision ID: 19c46f12b705
Revises: 7d7452e32d3e
Create Date: 2025-11-30 20:56:57.227202

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '19c46f12b705'
down_revision = '7d7452e32d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectvendorrequest', sa.Column('vendor_profile_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('projectvendorrequest_vendor_id_fkey'), 'projectvendorrequest', type_='foreignkey')
    op.create_foreign_key(None, 'projectvendorrequest', 'vendorprofile', ['vendor_profile_id'], ['id'], ondelete='SET NULL')
    op.drop_column('projectvendorrequest', 'vendor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectvendorrequest', sa.Column('vendor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projectvendorrequest', type_='foreignkey')
    op.create_foreign_key(op.f('projectvendorrequest_vendor_id_fkey'), 'projectvendorrequest', 'vendorprofile', ['vendor_id'], ['id'], ondelete='SET NULL')
    op.drop_column('projectvendorrequest', 'vendor_profile_id')
    # ### end Alembic commands ###
