"""Add budget, questions and requirements to project table, change all fields to be required, change start_date from datetime to enum

Revision ID: 1b3094dc43a1
Revises: 371da8f0c7b9
Create Date: 2025-11-26 10:32:37.820124

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b3094dc43a1'
down_revision = '371da8f0c7b9'
branch_labels = None
depends_on = None


def upgrade():
    projectstart = postgresql.ENUM('Within 30 days', 'Within 60 days', 'After 60+ days', name='projectstart')
    projectstart.create(op.get_bind(), checkfirst=True)
    op.execute(
        """
        ALTER TABLE project
        ALTER COLUMN start_date TYPE projectstart
        USING start_date::text::projectstart;
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.Enum('Within 30 days', 'Within 60 days', 'After 60+ days', name='projectstart'),
               nullable=False)
    op.add_column('project', sa.Column('budget', sa.Float(), nullable=False))
    op.add_column('project', sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('project', sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('project', 'description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('user', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('vendor', 'company', name='userrole'),
               nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendorprofile', 'employee_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vendorprofile', 'founded_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vendorprofile', 'turnover',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('vendorprofile', 'description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    op.execute("DROP TYPE projectstart")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'start_date',
               existing_type=sa.Enum('Within 30 days', 'Within 60 days', 'After 60+ days', name='projectstart'),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('vendorprofile', 'description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('vendorprofile', 'turnover',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('vendorprofile', 'founded_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vendorprofile', 'employee_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('vendor', 'company', name='userrole'),
               nullable=True)
    op.alter_column('user', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('project', 'description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.drop_column('project', 'requirements')
    op.drop_column('project', 'questions')
    op.drop_column('project', 'budget')
    # ### end Alembic commands ###
