"""Remove optional from fields in VendorProfile

Revision ID: 5dc780e65204
Revises: a5db75b2c976
Create Date: 2025-11-27 17:48:23.114209

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5dc780e65204'
down_revision = 'a5db75b2c976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendorprofile', 'main_goal',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vendorprofile', 'sales_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vendorprofile', 'admin_contact_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vendorprofile', 'company_website',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vendorprofile', 'min_project_size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('vendorprofile', 'avg_hourly_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendorprofile', 'avg_hourly_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('vendorprofile', 'min_project_size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('vendorprofile', 'company_website',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vendorprofile', 'admin_contact_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vendorprofile', 'sales_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vendorprofile', 'main_goal',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
