"""add_inn_to_user

Revision ID: 8552f62e74e4
Revises: 460dcbfe2557
Create Date: 2026-06-20 12:56:20.873571

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8552f62e74e4'
down_revision = '460dcbfe2557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('inn', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'inn')
    # ### end Alembic commands ###
