"""remove_vendor_profile_fields

Revision ID: 8fde706fa7de
Revises: 8552f62e74e4
Create Date: 2026-06-22 22:46:26.502823

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8fde706fa7de'
down_revision = '8552f62e74e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendorprofile', 'company_website',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('vendorprofile', 'employee_count')
    op.drop_column('vendorprofile', 'avg_hourly_rate')
    op.drop_column('vendorprofile', 'turnover')
    op.drop_column('vendorprofile', 'sales_email')
    op.drop_column('vendorprofile', 'admin_contact_phone')
    op.drop_column('vendorprofile', 'founded_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendorprofile', sa.Column('founded_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('vendorprofile', sa.Column('admin_contact_phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('vendorprofile', sa.Column('sales_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('vendorprofile', sa.Column('turnover', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('vendorprofile', sa.Column('avg_hourly_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('vendorprofile', sa.Column('employee_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('vendorprofile', 'company_website',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
