"""Add some fields to VendorProfile

Revision ID: a5db75b2c976
Revises: c5ae81b446db
Create Date: 2025-11-27 17:47:40.387082

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a5db75b2c976'
down_revision = 'c5ae81b446db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendorprofile', sa.Column('main_goal', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vendorprofile', sa.Column('sales_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vendorprofile', sa.Column('admin_contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vendorprofile', sa.Column('company_website', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vendorprofile', sa.Column('min_project_size', sa.Float(), nullable=True))
    op.add_column('vendorprofile', sa.Column('avg_hourly_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendorprofile', 'avg_hourly_rate')
    op.drop_column('vendorprofile', 'min_project_size')
    op.drop_column('vendorprofile', 'company_website')
    op.drop_column('vendorprofile', 'admin_contact_phone')
    op.drop_column('vendorprofile', 'sales_email')
    op.drop_column('vendorprofile', 'main_goal')
    # ### end Alembic commands ###
