"""Add ProjectShortlist table

Revision ID: b6624ba458b4
Revises: 9639885d9298
Create Date: 2026-01-22 12:50:05.131867

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b6624ba458b4'
down_revision = '9639885d9298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectshortlist',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_profile_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_profile_id'], ['vendorprofile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'vendor_profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projectshortlist')
    # ### end Alembic commands ###
