"""Change Enum value callable, doesn't affect db

Revision ID: c5ae81b446db
Revises: 1b3094dc43a1
Create Date: 2025-11-26 14:47:16.948010

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5ae81b446db'
down_revision = '1b3094dc43a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'start_date',
               existing_type=postgresql.ENUM('Within 30 days', 'Within 60 days', 'After 60+ days', name='projectstart'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'start_date',
               existing_type=postgresql.ENUM('Within 30 days', 'Within 60 days', 'After 60+ days', name='projectstart'),
               nullable=False)
    # ### end Alembic commands ###
