"""Add created_at to Project model

Revision ID: e64a4a576d35
Revises: a3f6b5ebfd82
Create Date: 2025-12-06 21:37:50.019882

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e64a4a576d35'
down_revision = 'a3f6b5ebfd82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
    op.execute(
        sa.text(
            "UPDATE project SET created_at = NOW() WHERE created_at IS NULL"
        )
    )
    op.alter_column(
        "project",
        "created_at",
        existing_type=sa.DateTime(),
        nullable=False,
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'created_at')
    # ### end Alembic commands ###
