"""Change sales_email type to EmailStr in VendorProfile

Revision ID: f418b537732e
Revises: 5dc780e65204
Create Date: 2025-11-27 17:52:21.025631

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f418b537732e'
down_revision = '5dc780e65204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
